// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClmPRcSvkvaJ5YgX3lP1AajUI1ekYjROA',
    appId: '1:474350260483:web:4b86cef0800e7e123d9936',
    messagingSenderId: '474350260483',
    projectId: 'krishiai-92781',
    authDomain: 'krishiai-92781.firebaseapp.com',
    storageBucket: 'krishiai-92781.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz322RfDhVpmcT8_dWxkfm7Esjmijqx-M',
    appId: '1:474350260483:android:1a0d43b1e0b817a13d9936',
    messagingSenderId: '474350260483',
    projectId: 'krishiai-92781',
    storageBucket: 'krishiai-92781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPRX1XMA-9s8mdZAjvT0acMgLzp3uPcdU',
    appId: '1:474350260483:ios:051817e5919d41c43d9936',
    messagingSenderId: '474350260483',
    projectId: 'krishiai-92781',
    storageBucket: 'krishiai-92781.firebasestorage.app',
    iosBundleId: 'com.example.krashiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPRX1XMA-9s8mdZAjvT0acMgLzp3uPcdU',
    appId: '1:474350260483:ios:051817e5919d41c43d9936',
    messagingSenderId: '474350260483',
    projectId: 'krishiai-92781',
    storageBucket: 'krishiai-92781.firebasestorage.app',
    iosBundleId: 'com.example.krashiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClmPRcSvkvaJ5YgX3lP1AajUI1ekYjROA',
    appId: '1:474350260483:web:14dd69d273cb6dde3d9936',
    messagingSenderId: '474350260483',
    projectId: 'krishiai-92781',
    authDomain: 'krishiai-92781.firebaseapp.com',
    storageBucket: 'krishiai-92781.firebasestorage.app',
  );
}
